### ISSUE TITLE
Some courses disappear between days

### ISSUE THREAD

**Issue by camiloaa** [zeta12ti/DuolingoCourseSwitcher#5]
Courses disappear randomly between days.

How to reproduce:
   - Add several courses from several languages (e.g: English from Italian, Italian from English, French from Italian, Spanish from French, German from French, German from Spanish).
  - Use duolingo in computer A during the day.
  - Use duoligo in computer B during night.
  - Next morning some courses will be missing from computer A in the morning, and some other courses will be missing from computer B in the afternoon.

It seems like localstorage("duo.state") doesn't keep track of all courses.

**Comment by zeta12ti** [comment]
duo.state only kept courses from base languages that you visited on that specific computer. It isn't synced between computers. It's a moot point now, since it keeps every course you've signed up for, unless you've deleted it.

The script now simply relists the courses that Duolingo already shows you. This includes all courses for which you have more than 0 experience and (I believe) any course that has the same base language as your current course. See the README for a new screenshot.

**Comment by camiloaa** [comment]
Not that this script is necessary any more, but I am surprised that you managed to misunderstand my report. I don't expect duo.state to be synced between machines. Courses that were **already** in the menu disappear randomly between days if I use more than one computer. 

So if I study Spanish in computer A, but then **don't** study Spanish in computer B, Spanish might or might not appear again in computer A next day. 

You can't rely in duo.state between days if you use more than a computer.
